version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    tty: true  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
    networks:
      - fullcycle    

  nodejs:
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    tty: true  
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && node index.js"  # Comando para instalar dependências e iniciar o servidor Node.js
    depends_on:
      - db
    networks:
      - fullcycle
  db:
    image: mysql:5.7
    container_name: db-mysql
    restart: always
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks:
      - fullcycle
networks:
  fullcycle:
    driver: bridge    

